MD_PATH: "songs-md/"
CHORD_MD_OPEN: "<"
CHORD_MD_CLOSE: ">"
CHORD_HTML_OPEN: "<code>"
CHORD_HTML_CLOSE: "</code>"

KEYS: 
  - "A"
  - "A#"
  - "B"
  - "C"
  - "C#"
  - "D"
  - "D#"
  - "E"
  - "F"
  - "F#"
  - "G"
  - "G#"